version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  python:
    build: ./ai
    ports:
      - "8000:8000"
    env_file:
      - ./ai/.env
    depends_on:
      - mongo

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - python

volumes:
  mongo-data:
